# Generated by Django 6.0.6 on 2026-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(default='autre', max_length=100),
        ),
    ]
