# Generated by Django 6.0.6 on 2026-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(blank=True, choices=[('bathroom', 'Bathroom'), ('kitchen', 'Kitchen'), ('furniture', 'Furniture'), ('lighting', 'Lighting'), ('materials', 'Materials'), ('wellness', 'Wellness')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
    ]
